name: CI pour AwesomePasswordCheker

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'  

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests with Maven and generate JaCoCo report
        run: mvn clean test

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/jacoco-report/  # Ce dossier peut contenir les rapports générés par JaCoCo
