name: CI pour AwesomePasswordCheker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 8 with Temurin
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin' 

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests with Maven and generate JaCoCo report
        run: mvn clean test

      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/jacoco-report/